GIFS = [
    'CgACAgUAAxkDAAK6uWBPFfOnQNMY4kOhHv5b6rHMu8uCAAJVAQACbtPYVpxV2ttmUDJzHgQ',
    'CgACAgUAAxkDAAK6u2BPFnFvKwzcJRz9ExXnccmrziafAAKrAAOD_zBVPLDfd_SPqi0eBA',
    'CgACAgQAAxkDAAK61GBPHlMSPT0PifsAAV3eVl-Iv4YdbQACaAgAAlZD0VEYs1ZphiAIUx4E'
]
